version: '3.8'
services:
  # Database services only
  db:
    image: postgres:15
    container_name: SahraTalkDB
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sahratalk_db}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGPASSWORD: ${POSTGRES_PASSWORD}  #
    ports:
      - "${POSTGRES_HOST_PORT:-5500}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-sahratalk_db}"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis:
    image: redis:7
    container_name: SahraTalkRedis
    restart: always
    env_file:
      - .env
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "${REDIS_HOST_PORT:-6379}:${REDIS_PORT:-6379}"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Backend service with proper dependency waiting
  backend:
    image: omarsalhi1/sahratalk-be:1.0
    container_name: SahraTalkBE
    env_file:
      - .env
    ports:
      - "${SERVER_PORT:-3500}:${SERVER_PORT:-3500}"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  redisdata: