version: '3.8'
services:
  backend:
    image: omarsalhi1/sahratalk-be:1.0
    container_name: SahraTalkBE
    env_file:
      - .env
    ports:
      - "3500:3000"
    depends_on:
      - db
      - redis
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: SahraTalkDB
    restart: always
    environment:
      POSTGRES_DB: sahratalk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: SahraTalkRedis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: