version: '3.8'
services:
  backend:
    image: ${{ secrets.DOCKER_USERNAME }}/sahratalk-be:1.0
    env_file:
      - .env
    ports:
      - "3500:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: sahratalk_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
    ports:
      - "5500:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always
    command: ["redis-server", "--requirepass", "${{ secrets.REDIS_PASSWORD }}"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata: